### ISSUE TITLE
ocaml library installation with travis-ocaml.sh stops at [Y/n] prompt.

### ISSUE THREAD

**Issue by katshun0307** [ocaml/ocaml-ci-scripts#285] opened 2019-03-11 00:34 UTC
I'm trying to test my OCaml library.
 
```
install: "bash -ex .travis-ocaml.sh; opam install core dune odoc; "
env:
  - OCAML_VERSION=4.06
```
However, the build job log stops at this [Y/n] prompt. 

```
<><> Fetching repository information ><><><><><><><><><><><><><><><><><><><><><>
[default] Initialised
User configuration:
  Updating ~/.bash_profile.
[NOTE] Make sure that ~/.bash_profile is well sourced in your ~/.bashrc.
<><> Creating initial switch (ocaml-base-compiler.4.06.1) <><><><><><><><><><><>
<><> Gathering sources ><><><><><><><><><><><><><><><><><><><><><><><><><><><><>
[ocaml-base-compiler.4.06.1] downloaded from https://github.com/ocaml/ocaml/archive/4.06.1.tar.gz
<><> Processing actions <><><><><><><><><><><><><><><><><><><><><><><><><><><><>
∗ installed base-bigarray.base
∗ installed base-threads.base
∗ installed base-unix.base
∗ installed ocaml-base-compiler.4.06.1
∗ installed ocaml-config.1
∗ installed ocaml.4.06.1
Done.
# Run eval $(opam env) to update the current shell environment
++opam config env
+eval 'OPAM_SWITCH_PREFIX='\''/home/travis/.opam/ocaml-base-compiler.4.06.1'\'';' export 'OPAM_SWITCH_PREFIX;' 'CAML_LD_LIBRARY_PATH='\''/home/travis/.opam/ocaml-base-compiler.4.06.1/lib/stublibs:Updated' by package 'ocaml'\'';' export 


# --- omitted --- #


  ∗ install ppx_expect              v0.11.1    [required by ppx_jane]
  ∗ install bin_prot                v0.11.0    [required by core_kernel]
  ∗ install ppx_bin_prot            v0.11.1    [required by ppx_jane]
  ∗ install ppx_jane                v0.11.0    [required by core]
  ∗ install splittable_random       v0.11.0    [required by core_kernel]
  ∗ install core_kernel             v0.11.1    [required by core]
  ∗ install core                    v0.11.3
===== ∗ 63 =====
Do you want to continue? [Y/n] 
```

**Comment by nekketsuuu** [comment] 2019-03-11 11:54
@katshun0307 It seems that this is a bug of your script, not a bug of `.travis-ocaml.sh`. Add an `--yes` option to `opam install core dune odoc`.

**Comment by katshun0307** [comment] 2019-03-13 12:19
You were right. Thank you.

**Comment by nekketsuuu** [comment] 2019-03-13 13:59
@katshun0307 You're welcome :) Could you close this issue, please?

**Closed** 2019-03-13 23:55 UTC
